### PR TITLE
Show name of dynamic struct when after creation like normal structs

### PR DESCRIPTION
**Pull request by ameligrana**
Hi! Cool package, noticed this little inconsistency, hope it helps

### CODE REVIEW

**Comment by AntonOresten** [comment]
Thanks for the PR!

Unfortunately I can't replicate this:
```julia
julia> struct A end |> typeof
Nothing
```

On a related note (but unrelated to the package), I actually noticed a discrepancy in Julia where function definitions return `nothing` when the functions belong to another module:

```julia
julia> (Base.getindex() = 1) |> typeof
Nothing

julia> (getindex() = 1) |> typeof # evaluated in module Main?
typeof(getindex) (singleton type of function getindex, subtype of Function)
```

And there's actually nothing special about Base, cause from the context of Base, the function does get returned:

```julia
julia> @eval Base begin
           getindex() = 1
       end
getindex (generic function with 183 methods)
```

Not sure if this behavior is intended, but maybe something similar is going on in the case of structs?

**Comment by ameligrana** [comment]
I think you are misunderstanding the intent. it's just that with a type you have

```julia
julia> struct A end
A # @dynamic instead doesn't print anything at the moment
```

**Comment by AntonOresten** [comment]
I understand what you mean, but I'm just not seeing the type get printed even for normal types, hence why I checked the type of the expression `struct A end` when evaluated, which was `Nothing`.

This is Julia on version 1.10.4
```julia
julia> struct A end # defines A, returns nothing

julia> A
A
```
Are you on another version perhaps?

**Comment by ameligrana** [comment]
I rechecked again, and you are right, it doesn't print anything. I don't know where I got the impression that it worked that way, probably because one of my packages mimick a sort of struct behaviour (https://github.com/JuliaDynamics/DynamicSumTypes.jl) and It prints, and I always assumed it worked like Julia structs. Sorry for the noise!

**Pull request closed without merging**
